### ISSUE TITLE
Unit tests fail on macOS

### ISSUE THREAD

**Issue by Phil108** [Fody/Fody#1014]
**Not a patron yet, but adding a bug anyways, following up on https://gitter.im/Fody/Fody?at=60dee49b457e19611a2e5c71**

Running unit tests on Rider macOS, 
* 125 of 410 tests fail for Fody/PropertyChanged [8aa2646]
* Rider freezes after 7 of 34 failed tests for Fody/ConfigureAwait [c22e4d0]

Running the tests with Visual Studio on macOS had similar results.

![Rider halts with ConfigureAwait](https://user-images.githubusercontent.com/86647932/124495941-0fe0a180-ddb9-11eb-9c25-e95b3e909c09.png)

![Failed tests of PropertyChanged](https://user-images.githubusercontent.com/86647932/124495945-1111ce80-ddb9-11eb-88ec-40af1af53da7.png)

**Comment by ltrzesniewski** [comment]
Thanks, but could you please provide a stack trace (or several if there are different ones)? I can't really do much with these screenshots...

Note that the failures are expected on the net472 target, as the .NET Framework is only available on Windows. The .NET Core tests are supposed to run fine though.

**Comment by ltrzesniewski** [comment]
I can reproduce a failure on WSL2, and I assume it's the same issue as on macOS.

I get the following with PropertyChanged when running `dotnet test -f netcoreapp3.0`:

```
[xUnit.net 00:00:00.83]     MappingFinderSingleBackingReadonlyFieldGet.Run [FAIL]
  Failed MappingFinderSingleBackingReadonlyFieldGet.Run [< 1 ms]
  Error Message:
   System.IO.DirectoryNotFoundException : Could not find a part of the path '/home/lucas/dev/PropertyChanged/Tests/bin/Debug/netcoreapp3.0/home/lucas/dev/PropertyChanged/Tests/bin/Debug/netcoreapp3.0/Tests.dll'.
  Stack Trace:
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at DefinitionFinder.FindType(Type typeToFind) in /home/lucas/dev/PropertyChanged/Tests/DefinitionFinder.cs:line 52
   at DefinitionFinder.FindType[T]() in /home/lucas/dev/PropertyChanged/Tests/DefinitionFinder.cs:line 42
   at MappingFinderSingleBackingReadonlyFieldGet.Run() in /home/lucas/dev/PropertyChanged/Tests/MappingFinder/MappingFinderSingleBackingReadonlyFieldGet.cs:line 12
```

End result: `Failed:    51, Passed:   154`

**Comment by ltrzesniewski** [comment]
I pushed the following fix to PropertyChanged: https://github.com/Fody/PropertyChanged/commit/20218eaeac15b5631a1bd8a70875936ae1905413

The problem comes from code like `Assembly.CodeBase.Replace("file:///", "")` which is wrong on Unix OSes as the third slash is the root directory, so you end up transforming an absolute path to an (incorrect) relative one. I used `Assembly.Location` instead, as `CodeBase` is obsolete.

I am now getting all the tests to pass on WSL2. @Phil108 you should be able to run the PropertyChanged tests on macOS successfully as well with the latest commit if you have the .NET 3.1 runtime installed.

BTW @SimonCropp, `netcoreapp3.0` is out of support so we should bump the TFM of the tests - I noticed that only .NET Framework tests are run on AppVeyor because of this. 😨

**Comment by Phil108** [comment]
@ltrzesniewski Great, for `dotnet test -f netcoreapp3.0` all the tests pass now. 

Running ConfigureAwait with `dotnet test -f netcoreapp3.1` gives me the attached output, which looks similar to what I got on Windows, so I guess it is because _ildasm.exe_ is missing on both my macOS and Windows machines.

Thank you so much for looking into it.

**Comment by tom-englert** [comment]
@ltrzesniewski I've tried to setup integration builds for Fody on Linux and MaxOS: https://dev.azure.com/tom-englert/Fody/_build
However also here tests fail, starting with
`[xUnit.net 00:00:01.18] FodyHelpers.Tests: Catastrophic failure: System.TypeLoadException: Could not load type of field 'Xunit.Runner.VisualStudio.VsExecutionSink:recorder' (4) due to: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
`
Any idea what's missing here?

**Comment by ltrzesniewski** [comment]
@tom-englert That message gets logged under:  
`Test run for /home/vsts/work/1/s/FodyHelpers.Tests/bin/Release/net472/FodyHelpers.Tests.dll (.NETFramework,Version=v4.7.2)`  
but you can't run .NET Framework tests on Unix OSes, you need to run `dotnet test -f netcoreapp3.1` because of this.

I just get a couple CRLF/LF issues in the integration tests in WSL. The Fody non-integration tests assume a Windows OS in many places though.

**Comment by tom-englert** [comment]
@ltrzesniewski that did the trick, thanks. (I should have been reading the whole message 😏)
Integration tests are running now
