### ISSUE TITLE
Enable FodyWeavers.xml to be changed according to solution configuration

### ISSUE THREAD

**Issue by bawr** [Fody/Fody#158]
For example, I don't want to run Costura on my debug builds, but I still want to use other weavers.

It's possible to include the Fody task conditionally, but I don't see a way of overriding the config file.

Another viable approach would be to enable per-configuration sections in FodyWeavers.xml.

I wouldn't mind creating a patch for this, but I'd like to know if this feature is desirable in mainline Fody, and which approach would be preferred. Or maybe I'm missing something, and I can already do this?

**Comment by SimonCropp** [comment]
What would be the benefit if this? Is costura too slow?

**Comment by bawr** [comment]
No, that's not the problem.

In my setup I normally need to reload a certain assembly from disk every time my application is run (because of reasons), but when I build for release I want to include it. I can do either with Costura's weaver attributes, but not dynamically.

Additionally, it could be handy in other situations - for example, if I'm using a logger weaver, maybe I don't want it on release. Obviously, every weaver could check if it's being included in a debug build and act accordingly, but IMHO that kind of control belongs on a higher level.

**Comment by SimonCropp** [comment]
I think you will cause yourself more problems by sometimes using costura only on certain configs. I suggest you instead take explicit control over the assembly loading by combining https://github.com/Fody/ModuleInit and your own custom version of this https://github.com/Fody/Costura/blob/master/Template/ILTemplate.cs 

Then you have full dynamic control over exactly what happens in release and debug

And this feature is not really useful for a logging weaver since all the log frameworks have support for levels and delegates for creating strings. anotar will soon support the later https://github.com/Fody/Anotar/issues/52#issuecomment-73787566

**Comment by bawr** [comment]
Thanks, that works for me. ;)

I was actually using Anotar as well, but I wasn't aware that it's going to support this.
