### ISSUE TITLE
dotCover missing async methods

### ISSUE THREAD

**Issue by dsarfati** [Fody/Fody#284]
Cross posting from the Anotar repo where I originally posted this
Fody/Anotar#86

Our team just started using Anotar and I'm noticing very odd behavior with dotCover when using LogTo statements. When we LogTo in our async method, the method no longer shows up in the dotCover coverage tree. When we make the method non async or comment out the LogTo it works fine. Here are some examples:

```c#
public Task TestLog()
{
    LogTo.Info("Test Log");

    return Task.CompletedTask;
}

public async Task TestAsync()
{
    await Task.Delay(1);
}

//This is the one that is missing!!!
public async Task TestAsyncLog()
{
    LogTo.Info("Test Log Async");
   
    await Task.Delay(1);
}
```
Not sure if it matters, but we are using NLog and when we tried it with the non-Anotar way of using NLog everything works fine.

**Comment by ESolovova** [comment]
I have investigated the issue on dotCover's side and it turned out that the problem is with "AnotarLogger" field which Anotar adds to compiler-generated implementations of IAsyncStateMachine interface:

```csharp
[CompilerGenerated]
private sealed class <TestAsyncLog>d__3 : IAsyncStateMachine
{
  public int <>1__state;
  public AsyncTaskMethodBuilder <>t__builder;
  public AsyncTestClass <>4__this;
  private TaskAwaiter <>u__1;
  private static ILog AnotarLogger;
...
```
In order to build the coverage tree, dotCover needs to match methods of compiler-generated classes with user methods. For this it uses method/class names, method parameters list and class fields list. Now dotCover doesn't check whether class fields are private, public or static. It just checks their names (special/not special) and types.

E.g. if there is an `async` method named `Foo` with parameters `(int i, bool b)`, the compiler will generate a new class named `<Foo>d__N` implementing IAsyncStateMachine interface. This class will have some fields with special names (like `int <>1__state`) and two fields with names i and b. When dotCover builds the coverage tree it puts all code from `<Foo>d__N` class under `Foo` method node. 

In case of presence of `AnotarLogger` field in the compiler-generated class, dotCover thinks that there should be a user method with parameters `(int i, bool b, ILog AnotarLogger)` and fails to build the coverage tree correctly.

I can fix the problem in the next dotCover release.

**Comment by ESolovova** [comment]
https://youtrack.jetbrains.com/issue/DCVR-8621

**Comment by SimonCropp** [comment]
@ESolovova thanks for handling this on your side
