### ISSUE TITLE
Problem when downgrading an add-in 

### ISSUE THREAD

**Issue by csnemes** [Fody/Fody#329]
It seems to me that Fody always uses the latest version of an add-in that can be found in the lib. The other day I had to downgrade my add-in to an earlier version in one of my project. During the compilation fody still used the newer version, I had to delete the newer files from the package lib folder. I believe this is a rare corner case, but still it's worth to mention. Is there a proper way to handle such situation (specify the version somewhere in config)?

**Comment by SimonCropp** [comment]
@csnemes unfortunately this is very difficult to solve. we would need to have intimate knowledge of how to extract the package version from the variety of ways nuget can store it (packages.config, project.json, packagereference etc). however in the new VS 2017 project system this is solved since the package list is passed in via MSBuild. so given this is an edge case, and it will gradually decrease in frequency as people move to the new project format, is it worth investing time in?

**Comment by csnemes** [comment]
I see, it's not that easy. Given that this is a rare situation and it is solved with the new VS I don't think it's worth the effort. Thanks for the explanation.
