### ISSUE TITLE
Fody should avoid running in design-time builds

### ISSUE THREAD

**Issue by davkean** [Fody/Fody#349]
NServiceBus filed a [bug](https://developercommunity.visualstudio.com/content/problem/49253/visual-studio-ide-does-not-recognize-project-refer.html) against us because their the project system/language service was failing to find their project references. I found that one cause was that Fody was running during what we call design-time builds and breaking the build. This prevents the language service from seeing references, source files, options, etc 

Open the NServiceBus solution (in VS 2017) without building and you will see warnings similar to:

```
Warning		Fody: AssemblyPath "E:\NServiceBus\src\NServiceBus.Core\obj\Release\NServiceBus.Core.dll" does not exists. If you have not done a build you can ignore this error.	NServiceBus.Core			
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	NServiceBus.Core		1	Active
```

My understanding is that Fody rewrites the binary after it has been compiled, which means that it should avoid being run in design-time builds. I've written a document that describes what design-time builds are, diagnosing them and how to play nicely with them here: https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md.

**Comment by SimonCropp** [comment]
@davkean thanks for raising this

Is the fix as simple as addin a 

```
  <Target
      AfterTargets="AfterCompile"
      Condition="'$(DesignTimeBuild)' != 'true'"
```

**Comment by davkean** [comment]
Yep, looks good.

Sent from my Windows 10 phone

**Comment by SimonCropp** [comment]
@bording i have released a beta with this 2.0.11-beta0001 can u verify it fixes your issue

**Comment by bording** [comment]
I'm not sure if this is doing what it's supposed to do or not. While using the instructions on the page @davkean linked to get design-time build logs, I saw evidence that `$(DesignTimeBuild)` was empty instead of `true`. 

For example, one of the log entries showed the following:
```
Target "FodyTarget" skipped, due to false condition; (Exists('@(IntermediateAssembly)') And '$(DesignTimeBuild)' != 'true') was evaluated as (Exists('obj\Debug\NServiceBus.Core.dll') And '' != 'true').
```

But the reason that was skipped was the first part of the condition, so the target would have been skipped with 2.0.10 as well.

@davkean Am I wrong in thinking that `$(DesignTimeBuild)` should be `true` in the *.designtime.log files? I even added a test target that printed the value of it via a Message task, and it was always empty in the log files.

On a side note, while debugging this, I discovered the ultimate source of the original problem I filed the issue about. We have another target in the project that was added recently, and it was using `DependsOnTargets`. and `BeforeTargets`. When I switched the `DependsOnTargets` to an `AfterTargets` instead, the IntelliSense results stopped breaking. I never did see an error in the designtime log files to indicate this was a problem, it was just something I stumbled upon.

@davkean Is this "`DependsOnTargets` breaking IntelliSense" something I should file an issue about? If so, which repo would be correct for it? This is for the legacy project system, btw.

**Comment by bording** [comment]
@davkean Any thoughts on my findings above? It's somewhat concerning that `$(DesignTimeBuild)` never actually appeared to be `true` in the design-time build logs. Should I file an issue about the `DependsOnTargets` vs. `AfterTargets` behavior?

**Comment by davkean** [comment]
@bording Can you attach some sample build logs?

**Comment by bording** [comment]
@davkean If you take a look at https://github.com/Particular/NServiceBus again, I've pushed up two branches that should repro the problem and demostrate how using `AfterTargets` instead fixes it. Take a look at the `intellisense-broken` and `intellisense-fixed` branches.

In those branches, there is a Target called "GenerateReleaseDate" which in those branches does nothing more than print out the value of ` $(DesignTimeBuild)`. 

Here is a snippet from the attached log file:
```
Target "GenerateReleaseDate" in file "C:\Code\NServiceBus\src\NServiceBus.Core\Licensing\GenerateReleaseDate.targets":
  Task "Message"
    The design-time build value is ''
  Done executing task "Message".
Done building target "GenerateReleaseDate" in project "NServiceBus.Core.csproj".
```
This log file also shows that the Fody target was skipped because the first part of the condition was false, and that `$(DesignTimeBuild)` was empty.

[logfile.zip](https://github.com/Fody/Fody/files/1043390/logfile.zip)

**Comment by davkean** [comment]
@bording Your observation is correct. I just walked through the code the legacy project system, and it never sets `DesignTimeBuild` - I've been stuck in new project system land for the past couple of years that I must have completely forgotten this.  I'll update my doc.

Behavior is as follows:

C++ and New Project System: DesignTimeBuild is set to true during design-time builds.
Legacy Project System: DesignTimeBuild is never set.

With regards to the AfterTargets/DependsOnTargets issue it's hard to know without seeing build logs that I can compare. Your ordering is could change, before you were saying "run me before CoreCompile (making sure that GetVersion is run before me)". Now your saying "run me after GetVersion or before CoreCompile whichever is run first"

**Comment by bording** [comment]
> With regards to the AfterTargets/DependsOnTargets issue it's hard to know without seeing build logs that I can compare. Your ordering is could change, before you were saying "run me before CoreCompile (making sure that GetVersion is run before me)". Now your saying "run me after GetVersion or before CoreCompile whichever is run first"

@davkean I believe I've finally figured out the issue:

```
C:\Code\NServiceBus\src\NServiceBus.Core\Licensing\GenerateReleaseDate.targets(5,38): error MSB4057: The target "GetVersion" does not exist in the project.
```
Which happens in the design-time build that happens after I restore packages for the first time after doing a `git clean`. The GetVersion target is part of the GitVersionTask package, so it appears that that even though the packages have been restored, the target isn't available yet, and that build failure seems to trigger the intellisense break for the other projects because a new design-time build never runs for them. I guess something about the design-time build is cached, which is why this persists across VS restarts.

Anyway, this clearly has nothing to do with Fody, and it doesn't seem to be anything that needs to be filed against VS, so I'll just fix my target and that should be it. Thanks!
