### ISSUE TITLE
Why is Mono.Cecil not a dependency 

### ISSUE THREAD

**Issue by tmfo** [Fody/Fody#403]
Why is Mono.Cecil part of the Fody package. Mono Cecil is a dependency.
What is the reason of your solution?

**Comment by jasonwoods-7** [comment]
I was about to ask a similar question about the usage of Mono.Cecil in Fody.

I looked into Fody's version of Cecil and it seems you're using a custom version of Cecil instead of the one published to NuGet.

From what I can tell, the latest Mono.Cecil on NuGet is jbevain/cecil@03a03b2, but from your check-in note on 89d6f5b, Fody seems to be using jbevain/cecil@b03852f.

That being said, I recently found a bug in Mono.Cecil (jbevain/cecil#448) which is preventing me from upgrading some of my projects to use Fody 2.x.

Assuming my understanding is correct, can Fody be updated to use at least the jbevain/cecil@021b7ce version of Mono.Cecil?

**Comment by SimonCropp** [comment]
@tmfo fody uses a custom build of cecil since the cecil nuget is not actively kept up to date

**Comment by SimonCropp** [comment]
@jasonwoods-7 i deployed 2.1.3 with the latests cecil

**Comment by jasonwoods-7** [comment]
@SimonCropp awesome! thanks!
