### ISSUE TITLE
Is it possible to debug the weaving process?

### ISSUE THREAD

**Issue by rjwestman** [Fody/Fody#426]
I couldn't find this anywhere in the Wiki, but I'm trying to build my first weaver and wanted to check some things that are happening during weaving. As such I wanted to set breakpoints within the Execute method of the weaver, but it never stops there. Is there something I can do to make it possible to debug the build/weaving process?

**Comment by tom-englert** [comment]
You can debug your weaver when you debug the unit tests.

**Comment by rjwestman** [comment]
So the answer is "No, you will need to take extra care with your unit tests to see if everything worked correctly"?

**Comment by SimonCropp** [comment]
it is possible to debug the process. but your questions is really "how do i debug an msbuild task" rather than "how to debug fody"

basically u need to either attach to the running instance of msbuild.exe or fire a Debugger.Launch.

But @tom-englert is correct. you should exercise as many of the scenarios in your tests. since it is cumbersome to debug VS

**Comment by reflection-emit** [comment]
I debug my weaver by outputing the stacktrace and sometimes also using LogInfo to temporarily output variable values. But most of the time I use the Stacktrace and analyse the created IL code. The Stacktrace is 95% of the time enough to find the errors.
I tried attaching to msbuild once and it was too painfull... Wouldn't recommend it.

**Comment by BobbyCannon** [comment]
I know this is very old but for others sake (like myself) I would like to suggest a way more visual example of exactly how to connect a debugger.

![image](https://github.com/Fody/Fody/assets/840590/9fb59bc4-74a1-48fa-aadd-049c40a4bddc)

Just put this line 

`System.Diagnostics.Debugger.Launch();`

In the BaseModuleWeaver.Execute method. When you build you'll be prompted to connect a debugger. Then just select the Visual Studio instance you want to used to debug. Since my weaver is in the same instance of VS, I can just select that one.

![image](https://github.com/Fody/Fody/assets/840590/1ee32536-c84f-4e47-983b-3fa4471ba3af)

Once you select the visual studio instance that contains the weaver project. You should hit a break point like so.

![image](https://github.com/Fody/Fody/assets/840590/1bd11d8b-59c2-4db3-b3cf-88625df18723)
