### ISSUE TITLE
Fody: An unhandled exception occurred- in InternalGetAssemblyName

### ISSUE THREAD

**Issue by tzachshabtay** [Fody/Fody#477]
My solution builds fine on both Windows and Mac. When building in Ubuntu 16.04.3 LTS, it fails:

```

Target FodyTarget:
      Fody: Fody (version 1.0.0.0) Executing
      Fody: ProjectDirectory: '/home/tshabtay/Personal/git/MonoAGS/Source/Engine/AGS.Engine/'.
      Fody: AssemblyPath: '/home/tshabtay/Personal/git/MonoAGS/Source/Engine/AGS.Engine/obj/Debug/AGS.Engine.dll'
      Fody: Found path to weavers file '/home/tshabtay/Personal/git/MonoAGS/Source/Engine/AGS.Engine/FodyWeavers.xml'.
      Fody: SolutionDirectory path is '/home/tshabtay/Personal/git/MonoAGS/'
      Fody: Finding weavers
      Fody: FindAddinDirectories:
      Fody:   No PackageDefinitions
      Fody:   Skipped SolutionDir/Packages convention '/home/tshabtay/Personal/git/MonoAGS/Packages' since it doesn't exist.
      Fody:   Skipped directory from Nuget Config since it could not be derived.
      Fody:   Scanning the MsBuildThisFileDirectory parent: /home/tshabtay/.nuget/packages/'.
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.1.4/propertychanged.fody.dll'
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.2.5/netclassicweaver/propertychanged.fody.dll'
      Fody:   Skipped scanning '/home/tshabtay/Personal/git/MonoAGS/Tools' since it doesn't exist.
      Fody:   Scanning NuGetPackageRoot '/home/tshabtay/.nuget/packages/'.
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.1.4/propertychanged.fody.dll'
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.2.5/netclassicweaver/propertychanged.fody.dll'
      Fody: No Weaver project file found.
    MSBUILD : error : Fody: An unhandled exception occurred:
    MSBUILD : error : Exception:
    MSBUILD : error : 
    MSBUILD : error : StackTrace:
    MSBUILD : error :   at (wrapper managed-to-native) System.Reflection.Assembly:InternalGetAssemblyName (string,Mono.MonoAssemblyName&,string&)
    MSBUILD : error :   at System.Reflection.AssemblyName.GetAssemblyName (System.String assemblyFile) [0x00014] in /run/build/mono/mcs/class/corlib/System.Reflection/AssemblyName.cs:421 
    MSBUILD : error :   at AssemblyVersionReader.GetAssemblyVersion (System.String path) [0x00000] in C:\projects\fody\Fody\AssemblyVersionReader.cs:11 
    MSBUILD : error :   at System.Linq.CachingComparer`2[TElement,TKey].SetElement (TElement element) [0x00000] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/OrderedEnumerable.cs:484 
    MSBUILD : error :   at System.Linq.OrderedEnumerable`1[TElement].TryGetFirst (System.Boolean& found) [0x00031] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/OrderedEnumerable.cs:258 
    MSBUILD : error :   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x00018] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/First.cs:59 
    MSBUILD : error :   at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/First.cs:40 
    MSBUILD : error :   at AddinFinder.FindAddinAssembly (System.String packageName) [0x00017] in C:\projects\fody\Fody\AddinFinder\AddinFilesEnumerator.cs:13 
    MSBUILD : error :   at Processor.FindAssemblyPath (System.String weaverName) [0x00000] in C:\projects\fody\Fody\WeaverAssemblyPathFinder.cs:6 
    MSBUILD : error :   at Processor.ProcessConfig (WeaverEntry weaverConfig) [0x00027] in C:\projects\fody\Fody\InstanceLinker\WeaversConfiguredInstanceLinker.cs:24 
    MSBUILD : error :   at Processor.ConfigureWhenWeaversFound () [0x00016] in C:\projects\fody\Fody\InstanceLinker\WeaversConfiguredInstanceLinker.cs:9 
    MSBUILD : error :   at Processor.FindWeavers () [0x00062] in C:\projects\fody\Fody\Processor.cs:117 
    MSBUILD : error :   at Processor.Inner () [0x00087] in C:\projects\fody\Fody\Processor.cs:88 
    MSBUILD : error :   at Processor.Execute () [0x00034] in C:\projects\fody\Fody\Processor.cs:49 
    MSBUILD : error : 
      Fody:   Finished Fody 11ms.
Done building target "FodyTarget" in project "AGS.Engine.csproj" -- FAILED.

Done building project "AGS.Engine.csproj" -- FAILED.

Build FAILED.

```

Tested with Fody 2.3.22, building from MonoDevelop 7.1 build 1291, using Mono 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4).

To reproduce, build my solution which can be found here: https://github.com/tzachshabtay/MonoAGS

Side note: your exception friendly printer (https://github.com/Fody/Fody/blob/3b238d48d9671a10352fbd42ec67d90c7597ebc8/FodyCommon/ExceptionExtensions.cs) does not print the type of the exception, which would be helpful here as it seems that the exception has en empty message.

**Comment by SimonCropp** [comment]
If u send me a pr that adds the exception type to the log i will merge and release. That should give us some more context on your error

**Comment by SimonCropp** [comment]
Can u also try the latest version of mono

**Comment by tzachshabtay** [comment]
Submitted #478 for the printout.
Getting the same error with mono 5.4.1.7

**Comment by SimonCropp** [comment]
ok i pushed the 478 pr. nuget might take an hour to refresh

**Comment by tzachshabtay** [comment]
Ok, I reproduced with the new version: the exception type is "System.IO.FileNotFoundException".

I looked in the paths it uses to search for the weavers based on the log: both files exist but as "PropertyChanged.Fody.dll" and not "propertychanged.fody.dll".
I copied both files to the same folder as "propertychanged.fody.dll", recompiled and it worked.

So the issue is definitely about case-sensitiveness in linux file system. 

One possible ugly solution, would be for AssemblyVersionReader to check if the file does not exist, and if it doesn't to iterate the files in the folder and look for a lower-case match, and if there's a match, to use that file path instead.
Maybe there are cleaner ways to resolve this, though.

**Comment by hanimv** [comment]
Hi @SimonCropp  @tzachshabtay 
I am getting this error in windows as well and since version 2.3.15. My VS solution has two projects. The fody addin, say MyAddin.Fody and its unit tests MyAddin.Fody.Tests




`1>------ Rebuild All started: Project: MyAddin.Fody, Configuration: Debug Any CPU ------
1>    Fody: Fody (version 2.3.23.0) Executing
1>MSBUILD : warning : Fody: No configured weavers. It is possible no weavers have been installed or a weaver has been installed into a project type that does not support install.ps1. It may be necessary to manually add that weaver to FodyWeavers.xm;. eg.
1>MSBUILD : warning : <Weavers>
1>MSBUILD : warning :     <WeaverName/>
1>MSBUILD : warning : </Weavers>
1>MSBUILD : warning : see https://github.com/Fody/Fody/wiki/SampleUsage
1>    Fody:   Finished Fody 32ms.
1>  MyAddin.Fody -> D:\_hanim\_workarea\FodyPackages\V2\MyAddin.Fody\bin\Debug\MyAddin.Fody.dll
1>    Fody:   Skipped Verifying assembly since it is disabled in configuration
1>    Fody:   Finished verification in 0ms.
2>------ Rebuild All started: Project: MyAddin.Fody.Test, Configuration: Debug Any CPU ------
2>    Fody: Fody (version 2.3.23.0) Executing
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Could not load file or assembly 'MyAddin.Fody.dll' or one of its dependencies. The system cannot find the file specified.
2>MSBUILD : error : Type:
2>MSBUILD : error : System.IO.FileNotFoundException
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at System.Reflection.AssemblyName.nGetFileInformation(String s)
2>MSBUILD : error :    at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
2>MSBUILD : error :    at AssemblyVersionReader.GetAssemblyVersion(String path)
2>MSBUILD : error :    at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
2>MSBUILD : error :    at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
2>MSBUILD : error :    at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
2>MSBUILD : error :    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
2>MSBUILD : error :    at AddinFinder.FindAddinAssembly(String packageName)
2>MSBUILD : error :    at Processor.FindAssemblyPath(String weaverName)
2>MSBUILD : error :    at Processor.ProcessConfig(WeaverEntry weaverConfig)
2>MSBUILD : error :    at Processor.ConfigureWhenWeaversFound()
2>MSBUILD : error :    at Processor.FindWeavers()
2>MSBUILD : error :    at Processor.Inner()
2>MSBUILD : error :    at Processor.Execute()
2>MSBUILD : error : Source:
2>MSBUILD : error : mscorlib
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : System.Reflection.AssemblyName nGetFileInformation(System.String)
2>MSBUILD : error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2>MSBUILD : error : Type:
2>MSBUILD : error : System.IO.FileNotFoundException
2>MSBUILD : error : 
2>    Fody:   Finished Fody 37ms.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========`

**Comment by SebastianStehle** [comment]
Same problem here: http://build.squidex.io/Squidex/squidex/728 ... Is there an workaround? I tried 2.3.14, but no luck.

**Comment by SebastianStehle** [comment]
A fix could be: https://github.com/Fody/Fody/pull/480/files ... I would like to test it, but I don't know how to create a nuget package out of it.

**Comment by SimonCropp** [comment]
thanks to @SebastianStehle  this is now deployed

**Comment by SebastianStehle** [comment]
Perfect, then I can delete my local package.
