### ISSUE TITLE
Weaver using symbols can't be tested using WeaverTestHelper.ExecuteTestRun

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#532]
WeaverTestHelper.ExecuteTestRun does not provide symbols to the weaver under test because the ReaderParameters are not setup properly and symbols are not written back.

PR & Tests will follow.

**Comment by tom-englert** [comment]
@ltrzesniewski doesn't it? Maybe the changes above already fix it?

**Comment by ltrzesniewski** [comment]
I admit I haven't tested this yet, but there's no reference to `WriterParameters.WriteSymbols` in `WeaverTestHelper`, so I assumed it wouldn't work.

**Comment by tom-englert** [comment]
I see, but maybe you'd better create a new issue, I would not like to commit that under the wrong title.

**Comment by ltrzesniewski** [comment]
I'd say it's related, since "using symbols" could be understood as "reading/writing symbols".
But if you'd rather not include the writing part here, I'll submit a PR when I'll have some time (I'm writing this from a tablet right now...).

**Comment by tom-englert** [comment]
OK, maybe your'e right, I'll add that to the same PR.

**Comment by ltrzesniewski** [comment]
Thanks! :smile:

**Comment by SimonCropp** [comment]
@tom-englert thanks for the PR. this is now deployed

**Comment by ltrzesniewski** [comment]
FYI this change uncovered an interesting problem in my weaver. It should be pretty uncommon but I thought I'd mention it here just in case.

Turns out writing debug information can influence the metadata Cecil emits.

InlineIL is commonly used by declaring `using static InlineIL.IL.Emit;`, and the `using static` directive differs from a simple `using` in that it *will* reference the metadata token of the imported type, not simply its name: the `ImportScope` table in the pdb will contain a `TypeRef` token, so when writing symbols, Cecil needs to add the required row to the `TypeRef` table. Other *"unusual"* directives such as `extern alias` seem to have a similar behavior.

If you then remove the `AssemblyRef` to the weaver library, for instance by setting `BaseModuleWeaver.ShouldCleanReference` to true, you'll end up with a `TypeRef` that references an invalid `AssemblyRef`. This makes PEVerify unhappy.

Here's what I use instead of `ShouldCleanReference` to work around the issue:

https://github.com/ltrzesniewski/InlineIL.Fody/blob/3bf0afe8dc7a53e4f1058af01e19529676165926/src/InlineIL.Fody/ModuleWeaver.cs#L87-L123

I don't know if changing the `ShouldCleanReference` logic would be worth it, given that most people don't probably use `using static` on a weaver library type. It's your call @SimonCropp.
