### ISSUE TITLE
Running Fody without FodyWeavers.xml

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#577]
This came to my mind after reading #571.
I already tried to start this as a discussion on gitter, but there was no response:

Now that Fody knows about most of the installed weaver packages due to #557 (except for some legacy ones, that did not update yet), we could simplify the usage regarding the FodyWeavers.xml file.

One could just install the NuGet package and compile the project, and for weavers that do not need any configuration it would work out of the box.

I could think of several options:

- Run without FodyWeavers.xml: run all well known installed weavers with an empty config
- Create a default FodyWeavers.xml containing all well known installed weavers if it does not exist
- Update an existing FodyWeavers.xml with missing well known installed weavers (would maybe require the possibility to disable a weaver)

Any thoughts about this?

**Comment by SimonCropp** [comment]
i like the idea.

but i think the doco for the targets convention needs to be done prior to this change

**Comment by ltrzesniewski** [comment]
The ordering of weavers could potentially be a concern, although I don't think it's likely to cause issues in practice. Just make sure it's consistent between builds.

**Comment by tom-englert** [comment]
@SimonCropp right, some docu changes are still pending, hopefully I can do this soon.
@ltrzesniewski I think this is far from being implemented, just let's collect some ideas and constraints. Probably creating the FodyWeavers.xml once if it does not exist is the most robust solution and solves the main problem, which is to always have to remember or read the documentation how the filename and the content should look like.

**Comment by ltrzesniewski** [comment]
Yeah I think I'd prefer for a file to be created rather than implicitly using every weaver. It would be strange for that file to be created/modified at compile time though, but there's no better way as far as I can see.
You'd also need to add the file explicitly to old-style project files, which would force the user to reload the project in VS after its first compilation.

Maybe we only should create the file if there are multiple weavers installed? If there's only one weaver just use it implicitly. I suppose most users only use one weaver, so that would solve most cases.
