### ISSUE TITLE
Fody delete all dll from bin folder on start debugging

### ISSUE THREAD

**Issue by GraySerg** [Fody/Fody#582]
Bug appears after update Fody to version 3.2.11 and higher.
I have a two solution in one folder
Server (have references to SharedDll)
Client (have references to SharedDll)
SharedDll (use Fody.PropertyChanged)
1.When I start Server it build successfully and start
2. Start Client using F5 it runs successfully.
3.Stop Client.
4. Start client again failed because all dll from client bin folders has been deleted.
5. If I delete all files from Client bin, then it build and start successfully. And again, and again.
On version 3.2.10 it works normally.

**Comment by tom-englert** [comment]
Can you post a sample project?

**Comment by GraySerg** [comment]
Yes. Here it is https://github.com/GraySerg/FodyBug

**Comment by GraySerg** [comment]
It's much simplier. It's enough to have to one project with Fody referenced by another project with Fody. First start  - success. On second all dll's deleted

**Comment by ltrzesniewski** [comment]
This is the problem:

![image](https://user-images.githubusercontent.com/7913492/47558393-4e88e300-d913-11e8-99e6-333f698d846e.png)

`FodyTarget` gets skipped, so it doesn't produce the needed `FodyUpdatedReferenceCopyLocalPaths`.

**Comment by ltrzesniewski** [comment]
The [MSBuild docs] say the following:

> - The target has no out-of-date outputs and is skipped. MSBuild evaluates the target and makes changes to items and properties as if the target had been run.
>
> To support incremental compilation, tasks must ensure that the `TaskParameter `attribute value of any `Output` element is equal to a task input parameter.

I'm not sure how to apply this to Fody and make `FodyTarget` support incremental builds *and* update `ReferenceCopyLocalPaths` at the same time.

**Comment by tom-englert** [comment]
@ltrzesniewski we can split the output in "added" and "removed" items instead of having one "updated" collection.
We then add the "added" items and remove the "removed" items. If the Fody task is sipped, both are empty and we don't change anything.

**Comment by tom-englert** [comment]
Or maybe this could help, too:
```xml
    <ItemGroup Condition="@(FodyUpdatedReferenceCopyLocalPaths)!=''">
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" />
      <ReferenceCopyLocalPaths Include="@(FodyUpdatedReferenceCopyLocalPaths)" />
    </ItemGroup>
```
I'll have to debug this to see if it works...

**Comment by tom-englert** [comment]
yes, just had the same idea just to use $(FodyExecutedWeavers)
just a stupid question: how do I force an incremental build in VS? It either builds, or does nothing saying everything is up to date.

**Comment by ltrzesniewski** [comment]
It still runs a build just fine for me.

Here's how I proceeded, if it helps:
- Using the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) extension, I enabled build logging (View -> Other Windows -> Build Logging, then click on the "play" icon).
- Rebuild all
- Build
- Open the second build in the binary log viewer (right click->Open logs...) - it's much nicer than the viewer provided by the extension.

**Comment by tom-englert** [comment]
#583 adds at least the condition, so incremental builds can work now. 
We can still think of some better solution and provide an improvement later...

**Comment by tom-englert** [comment]
Updated: store updated list in obj dir as suggested by @ltrzesniewski

**Comment by ltrzesniewski** [comment]
Nice! :+1:

I think you should be able to simplify this:

```xml
<FodyIntermediateCopyLocalFilesCacheExt Condition="'$(FodyIntermediateCopyLocalFilesCacheExt)' == ''">.fodyiclfc</FodyIntermediateCopyLocalFilesCacheExt>
<FodyIntermediateCopyLocalFilesCachePath>@(IntermediateAssembly->'%(FullPath)')$(FodyIntermediateCopyLocalFilesCacheExt)</FodyIntermediateCopyLocalFilesCachePath>
```

To this:

```xml
<FodyIntermediateCopyLocalFilesCachePath>@(IntermediateAssembly->'%(FullPath).fodyiclfc')</FodyIntermediateCopyLocalFilesCachePath>
```

I'll take a closer look tomorrow.

**Comment by ltrzesniewski** [comment]
I tested this a bit and it seems to work fine 🎉 

I looked at how MS handled similar stuff in `Microsoft.Common.CurrentVersion.targets`, and the `ResolveAssemblyReferences` target uses a similar caching strategy, which tells me it should be OK to take the same approach.

Here are some suggestions:

### FodyIntermediateCopyLocalFilesCachePath

I'd change the `FodyIntermediateCopyLocalFilesCachePath` property though in order to match how the `ResolveAssemblyReferencesStateFile` property is defined in the SDK:

```xml
<FodyIntermediateCopyLocalFilesCachePath Condition="'$(FodyIntermediateCopyLocalFilesCachePath)' == ''">$(IntermediateOutputPath)$(MSBuildProjectFile).FodyCache</FodyIntermediateCopyLocalFilesCachePath>
```

This is equivalent to how `ResolveAssemblyReferencesStateFile` is defined. Also, let's use a `.FodyCache` extension instead of `.fodyiclfc` 😉

(sorry for suggesting a change to this property once again)

### Storing a diff

I think your idea of storing a list of added/removed items is a good one, but it would require storing structured data in the cache file instead of a simple file list.
This is a "nice to have" change that can be made later.

###  `FodyTarget` inputs

This is unrelated to the PR, but I noticed that the `FodyTarget` inputs can be tweaked.

 They are defined as:
`@(IntermediateAssembly->'%(FullPath)');$(FodyKeyFilePath);$(ProjectWeaverXml)`

-  I don't think the transformation on `IntermediateAssembly` is necessary, and after looking at `Microsoft.Common.CurrentVersion.targets`, they use `@(IntermediateAssembly)` in their inputs. It doesn't hurt, though.
- Also, `$(FodyKeyFilePath)` is never defined. 

We could simplify the inputs to:
  `@(IntermediateAssembly);$(ProjectWeaverXml)`

---

So nothing really serious or important there - if you agree with these, you can take them into account or I can make the changes after the PR is merged, as you prefer.

**Comment by ltrzesniewski** [comment]
Actually I'll submit a separate PR for the inputs clean-up, since it's unrelated.

**Comment by tom-englert** [comment]
@SimonCropp it hit me today, and its really annoying - can you make a release?

**Comment by SimonCropp** [comment]
Yep. Sorry for the delay. This is now deployed, pending nuget updating its cache
