### ISSUE TITLE
Debugging weavers no longer possible

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#616]
since default debug type has changed to "embedded" in https://github.com/Fody/Fody/commit/e924e1f361ab36fd37b5dff77561965285f05eae I can't debug my weavers any longer. 
In the modules view it says "xyz.Fody - Binary was not built with debug information".
Setting debug type explicitly to e.g. "portable" fixes the problem.

Any thoughts? Are there additional settings needed so that VS can load embedded symbols?

**Comment by ltrzesniewski** [comment]
That's weird. It works for me. If anything it should work _better_ since VS doesn't even have to look for a separate file.

![image](https://user-images.githubusercontent.com/7913492/49292589-fadb5d80-f4ad-11e8-81eb-d379a52dc5a2.png)

Is your VS up to date? How are you debugging your weavers? My screenshot above is from a unit test.

**Comment by tom-englert** [comment]
I use a test project that uses the local weaver, and have a Debugger.Launch in the weavers Execute() method.
E.g. https://github.com/tom-englert/ILMerge.Fody

in common.props:
```xml
  <ItemGroup>
    <WeaverFiles Include="$(SolutionDir)$(SolutionName)\bin\$(Configuration)\Net46\$(SolutionName).dll" />
  </ItemGroup>
```
The test just uses fody to run this weaver during build to modify itself

**Comment by tom-englert** [comment]
P.S. just updated VS today...

**Comment by ltrzesniewski** [comment]
Ok, I can reproduce this with `Debugger.Launch()`, and I _think_ I understand the problem.

There is no path information, as the assembly is loaded from memory using the `Assembly.Load(byte[])` method.

This was changed in 2a75c61, as previously it was loaded using the `Assembly.Load(byte[], byte[])` overload which also loads symbols.

My _guess_ here is that `Assembly.Load(byte[])` doesn't load the embedded debug info, even if it exists 😢

**Comment by tom-englert** [comment]
Its interesting that if the .pdb exists, it will be loaded properly! 
So having embedded symbols in the weaver is somewhat useless.

**Comment by ltrzesniewski** [comment]
Wait, what? You're right, I just tested it. Turns out that when it's built with a portable PDB, the assembly contains the _path_ to the PDB:

![image](https://user-images.githubusercontent.com/7913492/49303299-a8a83580-f4c9-11e8-83e1-9d2307e7508b.png)

Damn... So VS can pick up that path and open the PDB, but it cannot use an embedded PDB? 😕 

Maybe it would be worth to send a bug report to Microsoft.
