### ISSUE TITLE
Fody does not work in the dotnet cli again

### ISSUE THREAD

**Issue by AsValeO** [Fody/Fody#668]
Cannot execute dotnet build/publish.
Azure DevOps CI/CD pipeline. 
Build agent with Visual Studio 2019. / .NET Core SDK 3.0.100-preview-010184
Multiple-projects solution. 
Projects have different Fody Weavers packages installed. Weavers packages depend on different versions of Fody. Fody package itself is not installed manually.
Command: 

> dotnet publish **/*.csproj

Error:

> error MSB4062: The "Fody.WeavingTask" task could not be loaded from the assembly C:\Users\VssAdministrator\.nuget\packages\fody\3.3.2\build\..\netstandardtask\Fody.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by ltrzesniewski** [comment]
You can't have multiple versions of Fody in the same build, because Fody gets loaded into the MSBuild process. Your build fails because MSBuild can't load multiple versions of the Fody assembly.

> Weavers packages depend on different versions of Fody. Fody package itself is not installed manually.

Install the latest version manually in all the projects that use weavers. The [usage](https://github.com/Fody/Home/blob/master/pages/usage.md) manual page explicitly instructs you to this, and for good reason.

The different weaver dependencies shouldn't be a concern unless you use very old weavers.

Alternatively, you could try to add the `/nr:false` argument to your dotnet script, but sticking to a single Fody version is the better approach.

**Comment by AsValeO** [comment]
Ok, ltrzesniewski, I got it.
But why classic msbuild handles this solution well? (In this case I specify solution file explicitly, not **/*.csproj)

**Comment by ltrzesniewski** [comment]
If you use the Azure Pipelines MSBuild task, it automatically adds `/nr:false` for you.

If you call MSBuild manually, then I don't know why it would work ¯\\\_(ツ)\_/¯

**Comment by AsValeO** [comment]
Yes, I've used Azure Pipelines MSBuild task.
Now all clear, thank you.

**Comment by SimonCropp** [comment]
@AsValeO 
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). .
