### ISSUE TITLE
EventHandler Memoryleak in InnerWeaver

### ISSUE THREAD

**Issue by raffzomp** [Fody/Fody#752]
#### You should already be a Patron
I am part of and posting on behalf of our company Erowa AG, which is already a Patron: https://opencollective.com/erowa-ag

#### Describe the issue
We use a large solution comprising around 160 projects with various nuget packages. For a while now, when we build our solution via msbuild on small build servers, we sporadically run into OutOfMemoryExceptions. We can reproduce the issue on our local dev machines when limiting msbuild to use one instance only. Upon investigation of the memory usage, we discovered that the memory constantly increases during the entire build and weave tasks until the cap of about 3,4GB is reached and the exception is thrown. See this first [screenshot](https://imgur.com/a/CaKbxtZ).

The further investigation pointed to an EventHandler leak in InnerWeaver as seen [here](https://imgur.com/4fuZ2oS).

The culprit can be found in InnerWeaver.cs of FodyIsolated and still can be found in the current master as seen [here](https://github.com/Fody/Fody/blob/master/FodyIsolated/InnerWeaver.cs#L119).

The AssemblyResolve deregistration is only made when an exception is thrown but not during the normal execution flow.
Simply moving the deregistration into the finally block solves this issue. A new memory evaluation with the fix can be seen [here](https://imgur.com/gTjfmsE). We went down from 3,4GB to around 800MB of final memory usage.

#### Minimal Repro

Any currently running weave task will leak memory.

#### Make an effort to fix the bug

We will submit a PR to fix the issue. We will not provide a test case for this though.

**Comment by BrunoJuchli** [comment]
Some more info (which I got from my colleagues who posted the issue):
Given a solution with multiple projects, even if you pass `/nodeReuse:false` to `msbuild`, the node is still being re-used for building subsequent projects. It's only discarded once the whole msbuild process ends.
Hence memory-leaks which occur during building a single project do affect building of other projects.

Also note, that the `OutOfMemoryException`s occur only sporadically. So it's a bit tricky to diagnose.

## Repro
Just in case someone's curious. This is not an exact repro, but it gives pointers how to increase the likelihood of running into the issue

- you need a solution with a lot of projects
- to increase the likelihood of the problem occuring, use `msbuild /m:1` (i.E. disabling parallel build). This will force msbuild to re-use the node for all projects in the solution.
- AFAIR there's a 32bits and a 64bits version of msbuild. You'll probably have to use the 32bits version, otherwise there's just so much more memory to waste before you run into problems ;-)

**Comment by SimonCropp** [comment]
Wow. very nice find. Also one of the best researched and articulated issues i have seen in a while. Well done.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by raffzomp** [comment]
Thank you for your kind words and thanks a lot for the quick deploy!
